export const DEFAULT_CATEGORIES = [
  'Vegetables',
  'Fruits',
  'Dairy',
  'Meat & Fish',
  'Baking',
  'Pantry',
  'Frozen',
  'Beverages',
  'Household',
  'Other',
] as const

/** Keyword → category name mapping for auto-assignment. */
export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  Vegetables: [
    'carrot',
    'onion',
    'potato',
    'tomato',
    'lettuce',
    'spinach',
    'broccoli',
    'cucumber',
    'pepper',
    'garlic',
    'celery',
    'mushroom',
    'zucchini',
    'cabbage',
    'kale',
    'avocado',
  ],
  Fruits: [
    'apple',
    'banana',
    'orange',
    'lemon',
    'lime',
    'berry',
    'strawberry',
    'blueberry',
    'grape',
    'melon',
    'mango',
    'pear',
    'peach',
    'pineapple',
  ],
  Dairy: [
    'milk',
    'cheese',
    'butter',
    'yogurt',
    'cream',
    'egg',
    'cottage',
    'mozzarella',
    'cheddar',
    'parmesan',
  ],
  'Meat & Fish': [
    'chicken',
    'beef',
    'pork',
    'salmon',
    'fish',
    'turkey',
    'bacon',
    'sausage',
    'ham',
    'steak',
    'shrimp',
    'tuna',
  ],
  Baking: [
    'flour',
    'sugar',
    'yeast',
    'baking',
    'vanilla',
    'cocoa',
    'chocolate',
    'icing',
    'sprinkle',
  ],
  Pantry: [
    'rice',
    'pasta',
    'oil',
    'vinegar',
    'salt',
    'peppercorn',
    'spice',
    'bean',
    'lentil',
    'cereal',
    'oat',
    'nut',
    'honey',
    'jam',
    'sauce',
    'stock',
    'broth',
    'can',
    'soup',
  ],
  Frozen: ['frozen', 'ice cream', 'pizza'],
  Beverages: [
    'water',
    'juice',
    'coffee',
    'tea',
    'soda',
    'beer',
    'wine',
    'drink',
    'lemonade',
  ],
  Household: [
    'soap',
    'shampoo',
    'detergent',
    'toilet',
    'paper',
    'tissue',
    'trash',
    'bag',
    'sponge',
    'cleaner',
  ],
}

export function guessCategoryName(itemName: string): string {
  const normalized = itemName.toLowerCase()
  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    if (keywords.some((kw) => normalized.includes(kw))) {
      return category
    }
  }
  return 'Other'
}

export const USUAL_ITEM_THRESHOLD = 3
export const USUAL_ITEM_WINDOW_DAYS = 28
